# Travis CI integration -- https://travis-ci.org/troglobit/mrouted
language: c
compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "TXLaXkIDGM9q6K+DGIwAJ5o+HVS6ih4p1c8MHyVkA4m0EdsdB74TVWHwyqQ2vrjlQcuTmYpQH3wCggH9Czo0Vm0Sdn+AROMMlAHQrcw6qPb0iRhZaDGu09n7GhUD0EoKM2y5OwC64Koc2aVSuLpQElQjyEPHLVVAwgwcgYgWS4Q="

addons:
  coverity_scan:
    project:
      name: "troglobit/mrouted"
      description: "mrouted | The Original Multicast Routing Daemon"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./configure --enable-rsrr"
    build_command:   "make"
    branch_pattern: master

script: ./configure --enable-rsrr && make
